# Generated by Django 4.1.6 on 2023-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenum', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
